# GitHub repositories to display in /projects page
github-repos: ['pycraigslist', 'youtube2audio', 'actransit-map', 'visuaudio', 'jupyterblack', 'astree', 'soil-moisture-display', 'personal-website-2']
